### ISSUE TITLE
[BUG] - Changing metric from columns to table

### ISSUE THREAD

**Issue by KarmitoHerry** [re-data/re-data#201]
**Describe the bug**
Hi re_data Team!
I found something not usual about implement metric at `dbt_project.yml`. I switch metric from column to table then I got an error.
```
13:33:39  Database Error in model re_data_z_score (models/anomalies/re_data_z_score.sql)
13:33:39    UPDATE/MERGE must match at most one source row for each target row
13:33:39    compiled SQL at target/run/re_data/models/anomalies/re_data_z_score.sql
```

**Expected behavior**
When i change the position on the setup, I expect there is not error at any level of monitoring. 
Temporary Solution : **_Delete the schema, and re-run the whole process_** 

Assumption : `re_data` store history before the metric has been change from column to table then engine recognize something wrong about switching place.

Hope for next release if developer do switch metric between columns and table , the engine doesn't crash

**To Reproduce**
Before , I miss understanding about metric : `distinct_table_rows` , this metric should use at table
```
re_data:monitored:
    - schema: analytics
      database: prod
      tables: 
        - name: fact_orders
          time_filter: localTime
          metrics:
            column:
              total:
                - avg
                - min
                - max
              storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
        - name: id_fact_items
          time_filter: localTime
          metrics:
            column:
              refId:
                - distinct_table_rows 
              storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
      actively_monitored: true
```
After , I understand the behavior of the metric, than i change the metric on `table`
```
re_data:monitored:
    - schema: analytics
      database: prod
      tables: 
        - name: fact_orders
          time_filter: localTime
          metrics:
            column:
              total:
                - avg
                - min
                - max
              storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
        - name: id_fact_items
          time_filter: localTime
          metrics:
            table:
              - distinct_table_rows  <<------ I place it here
            column:
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
      actively_monitored: true
```
then , i run command `re_data run` and i got load.

**Logs and additional context**
```
Running for time interval: 2022-01-24 00:00 - 2022-01-25 00:00 RUN
13:32:46  Running with dbt=1.0.1
13:32:46  Unable to do partial parsing because a project config has changed
13:32:47  Found 27 models, 26 tests, 0 snapshots, 0 analyses, 601 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
13:32:47  
13:32:51  Concurrency: 4 threads (target='prod')
13:32:51  
13:32:51  1 of 20 START table model analytics_re_data_result.re_data_monitored............ [RUN]
13:32:51  2 of 20 START incremental model analytics_re_data_result.re_data_run_results.... [RUN]
13:32:51  3 of 20 START table model analytics_re_data_result.re_data_run_started_at....... [RUN]
13:32:54  2 of 20 OK created incremental model analytics_re_data_result.re_data_run_results [MERGE (0.0 rows, 0 processed) in 2.73s]
13:32:54  3 of 20 OK created table model analytics_re_data_result.re_data_run_started_at.. [CREATE TABLE (1.0 rows, 0 processed) in 2.80s]
13:32:54  4 of 20 START table model analytics_re_data_result.re_data_columns.............. [RUN]
13:32:54  1 of 20 OK created table model analytics_re_data_result.re_data_monitored....... [CREATE TABLE (6.0 rows, 0 processed) in 2.84s]
13:32:56  4 of 20 OK created table model analytics_re_data_result.re_data_columns......... [CREATE TABLE (4.6k rows, 10.0 MB processed) in 2.71s]
13:32:56  5 of 20 START incremental model analytics_re_data_result.re_data_columns_over_time [RUN]
13:32:56  6 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_part0 [RUN]
13:32:56  7 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_part1 [RUN]
13:32:56  8 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_part2 [RUN]
13:32:59  7 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_part1 [CREATE TABLE (0.0 rows, 0 processed) in 2.07s]
13:32:59  9 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_part3 [RUN]
13:32:59  8 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_part2 [CREATE TABLE (0.0 rows, 0 processed) in 2.55s]
13:32:59  10 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_thread1 [RUN]
13:32:59  5 of 20 OK created incremental model analytics_re_data_result.re_data_columns_over_time [MERGE (469.0 rows, 716.7 KB processed) in 2.66s]
13:32:59  11 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_thread2 [RUN]
13:32:59  6 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_part0 [CREATE TABLE (0.0 rows, 0 processed) in 2.81s]
13:32:59  12 of 20 START incremental model analytics_re_data_result.re_data_schema_changes [RUN]
13:33:01  9 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_part3 [CREATE TABLE (0.0 rows, 0 processed) in 2.28s]
13:33:01  13 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_thread0 [RUN]
13:33:03  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`id_fact_items`
13:33:03  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`id_fact_orders`
13:33:04  12 of 20 OK created incremental model analytics_re_data_result.re_data_schema_changes [MERGE (0.0 rows, 298.5 KB processed) in 4.99s]
13:33:04  14 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_thread3 [RUN]
13:33:05  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`sg_fact_orders`
13:33:06  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`id_fact_items`
13:33:07  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`th_fact_items`
13:33:08  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`sg_fact_items`
13:33:10  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`th_fact_items`
13:33:12  10 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_thread1 [CREATE TABLE (0.0 rows, 0 processed) in 13.20s]
13:33:13  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`sg_fact_items`
13:33:15  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`id_fact_orders`
13:33:15  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`sg_fact_orders`
13:33:16  14 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_thread3 [CREATE TABLE (0.0 rows, 0 processed) in 11.46s]
13:33:16  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`th_fact_orders`
13:33:18  13 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_thread0 [CREATE TABLE (0.0 rows, 0 processed) in 17.03s]
13:33:27  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`th_fact_orders`
13:33:29  11 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_thread2 [CREATE TABLE (0.0 rows, 0 processed) in 30.23s]
13:33:29  15 of 20 START incremental model analytics_re_data_result.re_data_base_metrics.. [RUN]
13:33:34  15 of 20 OK created incremental model analytics_re_data_result.re_data_base_metrics [MERGE (28.0 rows, 5.6 MB processed) in 5.02s]
13:33:34  16 of 20 START view model analytics_re_data_result.re_data_last_metrics......... [RUN]
13:33:34  17 of 20 START view model analytics_re_data_result.re_data_last_stats........... [RUN]
13:33:34  18 of 20 START view model analytics_re_data_result.re_data_metrics.............. [RUN]
13:33:35  16 of 20 OK created view model analytics_re_data_result.re_data_last_metrics.... [OK in 1.04s]
13:33:35  17 of 20 OK created view model analytics_re_data_result.re_data_last_stats...... [OK in 1.13s]
13:33:35  19 of 20 START incremental model analytics_re_data_result.re_data_z_score....... [RUN]
13:33:36  18 of 20 OK created view model analytics_re_data_result.re_data_metrics......... [OK in 1.16s]
13:33:39  19 of 20 ERROR creating incremental model analytics_re_data_result.re_data_z_score [ERROR in 3.79s]
13:33:39  20 of 20 SKIP relation analytics_re_data_result.re_data_alerting................ [SKIP]
13:33:39  
13:33:39  Finished running 5 incremental models, 11 table models, 4 view models in 51.98s.
13:33:39  
13:33:39  Completed with 1 error and 0 warnings:
13:33:39  
13:33:39  Database Error in model re_data_z_score (models/anomalies/re_data_z_score.sql)
13:33:39    UPDATE/MERGE must match at most one source row for each target row
13:33:39    compiled SQL at target/run/re_data/models/anomalies/re_data_z_score.sql
13:33:39  
13:33:39  Done. PASS=18 WARN=0 ERROR=1 SKIP=1 TOTAL=20
Traceback (most recent call last):
  File "/opt/homebrew/bin/re_data", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/re_data/command_line.py", line 117, in run
    completed_process.check_returncode()
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['dbt', 'run', '--models', 'package:re_data', '--vars', '{"re_data:time_window_start": "2022-01-24 00:00:00", "re_data:time_window_end": "2022-01-25 00:00:00", "re_data:anomaly_detection_window_start": "2021-12-25 00:00:00"}']' returned non-zero exit status 1.
```

**Comment by KarmitoHerry** [comment]
I found the anomaly behavior about `distinct_table_rows` , this metric just want to work if I added when no schema from `re_data` has been generated on my database.

this `dbt_project.yml` before adding on two other table's , i just added on `SG`

```
name: 'fc_re_data'
version: '1.0.0'
config-version: 2

# Setup profile for re_data in your ~/.dbt/profile.yml file
profile: 'my-bigquery-db'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets: ["target", "dbt_modules", "dbt_packages"]

models:
  re_data:
    enabled: true
    +schema: re_data_result

vars:
  re_data:time_window_start: '{{ (run_started_at - modules.datetime.timedelta(1)).strftime("%Y-%m-%d 00:00:00") }}'
  re_data:time_window_end: '{{ run_started_at.strftime("%Y-%m-%d 00:00:00") }}'
  re_data:anomaly_detection_look_back_days: 30
  re_data:alerting_z_score: 3
  re_data:schemas:
    - analytics
  re_data:monitored:
    - schema: analytics
      tables: 
        - name: id_fact_orders
          time_filter: localTime
          metrics:
            column:
              total:
                - avg
                - min
                - max
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
              refId: 
                - duplicate_rows
        - name: id_fact_items
          time_filter: localTime
        - name: sg_fact_orders
          time_filter: localTime
          metrics:
            column:
              total:
                - avg
                - min
                - max
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
              refId: 
                - duplicate_rows
        - name: sg_fact_items
          time_filter: localTime
          metrics:
            table:
              - distinct_table_rows
            column:
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
        - name: th_fact_orders
          time_filter: localTime
          metrics:
            column:
              total:
                - avg
                - min
                - max
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
              refId: 
                - duplicate_rows
        - name: th_fact_items
          time_filter: localTime
        - name: compare_apac_vs_country
          time_file: localDate
          metrics:
            table:
              - compare_id_rows_count
              - compare_sg_rows_count
              - compare_th_rows_count
      actively_monitored: true
  re_data:metrics_base:
    table:
      - row_count
      - freshness
    column:
      numeric: []
      text: []
``` 
After adding for two other fact_items table
```
name: 'fc_re_data'
version: '1.0.0'
config-version: 2

# Setup profile for re_data in your ~/.dbt/profile.yml file
profile: 'my-bigquery-db'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets: ["target", "dbt_modules", "dbt_packages"]

models:
  re_data:
    enabled: true
    +schema: re_data_result

vars:
  re_data:time_window_start: '{{ (run_started_at - modules.datetime.timedelta(1)).strftime("%Y-%m-%d 00:00:00") }}'
  re_data:time_window_end: '{{ run_started_at.strftime("%Y-%m-%d 00:00:00") }}'
  re_data:anomaly_detection_look_back_days: 30
  re_data:alerting_z_score: 3
  re_data:schemas:
    - analytics
  re_data:monitored:
    - schema: analytics
      tables: 
        - name: id_fact_orders
          time_filter: localTime
          metrics:
            column:
              total:
                - avg
                - min
                - max
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
              refId: 
                - duplicate_rows
        - name: id_fact_items
          time_filter: localTime
          metrics:
            table:
              - distinct_table_rows
            column:
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count  
        - name: sg_fact_orders
          time_filter: localTime
          metrics:
            column:
              total:
                - avg
                - min
                - max
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
              refId: 
                - duplicate_rows
        - name: sg_fact_items
          time_filter: localTime
          metrics:
            table:
              - distinct_table_rows
            column:
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
        - name: th_fact_orders
          time_filter: localTime
          metrics:
            column:
              total:
                - avg
                - min
                - max
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count
              refId: 
                - duplicate_rows
        - name: th_fact_items
          time_filter: localTime
          metrics:
            table:
              - distinct_table_rows
            column:
              sh_storeId:
                - nulls_count
              paymentMethod:
                - nulls_count 
        - name: compare_apac_vs_country
          time_file: localDate
          metrics:
            table:
              - compare_id_rows_count
              - compare_sg_rows_count
              - compare_th_rows_count
      actively_monitored: true
  re_data:metrics_base:
    table:
      - row_count
      - freshness
    column:
      numeric: []
      text: []
```
After iIrun it , I got this error 
```

Running for time interval: 2022-01-26 00:00 - 2022-01-27 00:00 RUN
04:06:21  Running with dbt=1.0.1
04:06:21  Unable to do partial parsing because a project config has changed
04:06:22  Found 28 models, 26 tests, 0 snapshots, 0 analyses, 604 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
04:06:22  
04:06:23  Concurrency: 4 threads (target='prod')
04:06:23  
04:06:23  1 of 20 START table model analytics_re_data_result.re_data_monitored............ [RUN]
04:06:23  2 of 20 START incremental model analytics_re_data_result.re_data_run_results.... [RUN]
04:06:23  3 of 20 START table model analytics_re_data_result.re_data_run_started_at....... [RUN]
04:06:25  3 of 20 OK created table model analytics_re_data_result.re_data_run_started_at.. [CREATE TABLE (1.0 rows, 0 processed) in 2.20s]
04:06:25  4 of 20 START table model analytics_re_data_result.re_data_columns.............. [RUN]
04:06:25  2 of 20 OK created incremental model analytics_re_data_result.re_data_run_results [MERGE (0.0 rows, 0 processed) in 2.42s]
04:06:26  1 of 20 OK created table model analytics_re_data_result.re_data_monitored....... [CREATE TABLE (7.0 rows, 0 processed) in 3.35s]
04:06:28  4 of 20 OK created table model analytics_re_data_result.re_data_columns......... [CREATE TABLE (4.6k rows, 10.0 MB processed) in 2.89s]
04:06:28  5 of 20 START incremental model analytics_re_data_result.re_data_columns_over_time [RUN]
04:06:28  6 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_part0 [RUN]
04:06:28  7 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_part1 [RUN]
04:06:28  8 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_part2 [RUN]
04:06:31  7 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_part1 [CREATE TABLE (0.0 rows, 0 processed) in 2.69s]
04:06:31  9 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_part3 [RUN]
04:06:31  8 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_part2 [CREATE TABLE (0.0 rows, 0 processed) in 2.73s]
04:06:31  10 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_thread1 [RUN]
04:06:31  6 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_part0 [CREATE TABLE (0.0 rows, 0 processed) in 2.92s]
04:06:31  11 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_thread2 [RUN]
04:06:31  5 of 20 OK created incremental model analytics_re_data_result.re_data_columns_over_time [MERGE (478.0 rows, 886.2 KB processed) in 3.11s]
04:06:31  12 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_thread0 [RUN]
04:06:33  9 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_part3 [CREATE TABLE (0.0 rows, 0 processed) in 2.61s]
04:06:33  13 of 20 START incremental model analytics_re_data_result.re_data_schema_changes [RUN]
04:06:35  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`id_fact_items`
04:06:35  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`sg_fact_items`
04:06:36  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`compare_apac_vs_country`
04:06:38  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`id_fact_items`
04:06:39  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`th_fact_items`
04:06:39  13 of 20 OK created incremental model analytics_re_data_result.re_data_schema_changes [MERGE (0.0 rows, 418.7 KB processed) in 5.77s]
04:06:39  14 of 20 START table model analytics_re_data_result.re_data_last_base_metrics_thread3 [RUN]
04:06:41  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`sg_fact_items`
04:06:41  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`compare_apac_vs_country`
04:06:42  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`sg_fact_orders`
04:06:44  12 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_thread0 [CREATE TABLE (0.0 rows, 0 processed) in 12.49s]
04:06:44  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`id_fact_orders`
04:06:44  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`th_fact_items`
04:06:46  11 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_thread2 [CREATE TABLE (0.0 rows, 0 processed) in 15.39s]
04:06:56  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`sg_fact_orders`
04:06:58  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`id_fact_orders`
04:06:58  10 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_thread1 [CREATE TABLE (0.0 rows, 0 processed) in 27.19s]
04:06:59  [re_data_log] - start computing metrics for table:`prod`.`analytics`.`th_fact_orders`
04:07:14  [re_data_log] - finished computing metrics for table:`prod`.`analytics`.`th_fact_orders`
04:07:17  14 of 20 OK created table model analytics_re_data_result.re_data_last_base_metrics_thread3 [CREATE TABLE (0.0 rows, 0 processed) in 37.54s]
04:07:17  15 of 20 START incremental model analytics_re_data_result.re_data_base_metrics.. [RUN]
04:07:24  15 of 20 ERROR creating incremental model analytics_re_data_result.re_data_base_metrics [ERROR in 7.07s]
04:07:24  16 of 20 SKIP relation analytics_re_data_result.re_data_last_metrics............ [SKIP]
04:07:24  17 of 20 SKIP relation analytics_re_data_result.re_data_last_stats.............. [SKIP]
04:07:24  18 of 20 SKIP relation analytics_re_data_result.re_data_metrics................. [SKIP]
04:07:24  19 of 20 SKIP relation analytics_re_data_result.re_data_z_score................. [SKIP]
04:07:24  20 of 20 SKIP relation analytics_re_data_result.re_data_alerting................ [SKIP]
04:07:24  
04:07:24  Finished running 11 table models, 5 incremental models, 4 view models in 61.80s.
04:07:24  
04:07:24  Completed with 1 error and 0 warnings:
04:07:24  
04:07:24  Database Error in model re_data_base_metrics (models/metrics/types/base/re_data_base_metrics.sql)
04:07:24    UPDATE/MERGE must match at most one source row for each target row
04:07:24    compiled SQL at target/run/re_data/models/metrics/types/base/re_data_base_metrics.sql
04:07:24  
04:07:24  Done. PASS=14 WARN=0 ERROR=1 SKIP=5 TOTAL=20
Traceback (most recent call last):
  File "/opt/homebrew/bin/re_data", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/re_data/command_line.py", line 117, in run
    completed_process.check_returncode()
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['dbt', 'run', '--models', 'package:re_data', '--vars', '{"re_data:time_window_start": "2022-01-26 00:00:00", "re_data:time_window_end": "2022-01-27 00:00:00", "re_data:anomaly_detection_window_start": "2021-12-27 00:00:00"}']' returned non-zero exit status 1.
```

**Comment by mateuszklimek** [comment]
Hey @KarmitoHerry I think our recent update should solve this problem.
