### ISSUE TITLE
[BUG] Failed to generate overview "non-zero exit status"

### ISSUE THREAD

**Issue by moseleyi** [re-data/re-data#385]
**Describe the bug**
Can't generate the overview

**Expected behavior**
Report gets generated

**To Reproduce**
`re_data overview generate`

**Screenshots**
![image](https://user-images.githubusercontent.com/16131590/214019234-b58cd536-a9fe-4918-8892-6da322dbde1e.png)

**Logs and additional context**

```
dbt run-operation generate_overview --args end_date: '2023-01-23'
interval: days:1
monitored_path: D:\projects\simplr\simplr-analytics\target\re_data\monitored.json
overview_path: D:\projects\simplr\simplr-analytics\target\re_data\overview.json
start_date: '2023-01-16'

←[0m10:35:41  Running with dbt=1.3.2
←[0m10:35:42  11:35:42 + [re_data] interval length in seconds is 86400
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\re_data.exe\__main__.py", line 7, in <module>
  File "C:\Python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python38\lib\site-packages\re_data\tracking.py", line 108, in decorated
    raise e
  File "C:\Python38\lib\site-packages\re_data\tracking.py", line 95, in decorated
    fun(*args, **kwargs)
  File "C:\Python38\lib\site-packages\re_data\version.py", line 41, in decorated
    return fun(*args, **kwargs)
  File "C:\Python38\lib\site-packages\re_data\command_line.py", line 310, in generate
    completed_process.check_returncode()
  File "C:\Python38\lib\subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['dbt', 'run-operation', 'generate_overview', '--args', "end_date: '2023-01-23'\ninterval: days:1\nmonitored_path: D:\\projects\\simplr\\simplr-analytics\\target\\re_data\\monitored.json\noverview_path: D:\\projects\\simplr\\simplr-analytics\\target\\re_data\\overview.json\nstart_date: '2023-01-16'\n"]' returned non-zero exit status 3221225477.
```

I did have a problem with `jsonschema` but not sure if that could be the problem. The `jsonschema` package I have installed is newer than re_data package wants to use. Here's the screenshot:

![image](https://user-images.githubusercontent.com/16131590/214019425-de7e3160-5a94-4ef2-af9f-021b103df94b.png)

**Comment by sthornton73** [comment]
Howdy, was there a resolution identified for this issue? I'm seeing it in re_data v0.11.0 and dbt v1.8.1 in Windows Intellij with py v 3.11.9.

**Comment by sthornton73** [comment]
Ok found the issue, had 2 versions of dbt and looks like re_data overview generate was getting the older version. Removed all dbt versions and installed latest, this resolved the issue.
