### ISSUE TITLE
[BUG] errors on dbt compile

### ISSUE THREAD

**Issue by dbrtly** [re-data/re-data#99]
**Describe the bug**
``` dbt_modules/re_data/dbt_project.yml
# I commented out this line
# profile: 're_data_postgres'
```

then I ran:
``` shell
(.venv) daniel@dbrtly-MBP dbt_shop % dbt compile
Running with dbt=0.20.0

Found 26 models, 44 tests, 0 snapshots, 0 analyses, 647 macros, 0 operations, 0 seed files, 4 sources, 1 exposure

20:04:50 | Concurrency: 4 threads (target='dev')
20:04:50 | 
Encountered an error:
Runtime Error
  Runtime Error in model re_data_base_metrics (models/intermediate/re_data_base_metrics.sql)
    404 Not found: Dataset daniel-bartley-sandbox:dbt_shop_re was not found in location US
    
    (job ID: 69d805c5-c7e3-4bf0-9cdd-ee8357fd0d38)
```
I manually created the dataset to see what would happen.
    
``` shell
(.venv) daniel@dbrtly-MBP dbt_shop % dbt compile
Running with dbt=0.20.0
[WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- seeds

Found 26 models, 44 tests, 0 snapshots, 0 analyses, 647 macros, 0 operations, 0 seed files, 4 sources, 1 exposure

20:07:51 | Concurrency: 4 threads (target='dev')
20:07:51 | 
Encountered an error:
Runtime Error
  Runtime Error in model re_data_freshness_inc (models/intermediate/re_data_freshness_inc.sql)
    404 Not found: Table daniel-bartley-sandbox:dbt_shop_re.re_data_tables was not found in location US
    
    (job ID: 62bf3af6-1656-4fb2-88d0-42166b550568)
 ```

**Expected behavior**

This command should run with no errors related to the re_data package.
```
dbt compile 
```

**To Reproduce**
Assuming you start with a functional project named jaffle_shop (1 source, 1 additional model) with python, a valid profile, permissions, etc. The following should run without an error:

``` shell
cd jaffle_shop
 {
        echo 'packages:'
        echo '  - package: re-data/re_data'
        echo "    version: ['>=0.2.0', '<0.3.0']"
} > packages.yml
dbt deps
dbt compile
```

**Screenshots**
Not UI related

**Logs and additional context**
2021-08-02 10:07:52.639923 (Thread-2): Finished running node model.re_data.re_data_schema_changes
2021-08-02 10:07:52.640174 (Thread-1): Finished running node model.re_data.re_data_freshness_inc
2021-08-02 10:07:52.640377 (Thread-4): Finished running node model.re_data.re_data_base_metrics
2021-08-02 10:07:52.641022 (MainThread): Connection 'master' was properly closed.
2021-08-02 10:07:52.641607 (MainThread): Connection 'model.re_data.re_data_freshness_inc' was properly closed.
2021-08-02 10:07:52.641744 (MainThread): Connection 'model.re_data.re_data_schema_changes' was properly closed.
2021-08-02 10:07:52.641823 (MainThread): Connection 'model.dbt_shop.customer_orders' was properly closed.
2021-08-02 10:07:52.641893 (MainThread): Connection 'model.re_data.re_data_base_metrics' was properly closed.
2021-08-02 10:07:52.642121 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b8f1f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b948f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bcd3a30>]}
2021-08-02 10:07:52.642348 (MainThread): Flushing usage events
2021-08-02 10:07:53.707659 (MainThread): Encountered an error:
2021-08-02 10:07:53.707887 (MainThread): Runtime Error
  Runtime Error in model re_data_freshness_inc (models/intermediate/re_data_freshness_inc.sql)
    404 Not found: Table daniel-bartley-sandbox:dbt_shop_re.re_data_tables was not found in location US
    
    (job ID: 62bf3af6-1656-4fb2-88d0-42166b550568)
2021-08-02 10:07:53.710593 (MainThread): Traceback (most recent call last):
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/main.py", line 203, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/main.py", line 256, in run_from_args
    results = task.run()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 425, in run
    result = self.execute_with_hooks(selected_uids)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 384, in execute_with_hooks
    res = self.execute_nodes()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 339, in execute_nodes
    self.run_queue(pool)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 246, in run_queue
    self._raise_set_error()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 222, in _raise_set_error
    raise self._raise_next_tick
dbt.exceptions.RuntimeException: Runtime Error
  Runtime Error in model re_data_freshness_inc (models/intermediate/re_data_freshness_inc.sql)
    404 Not found: Table daniel-bartley-sandbox:dbt_shop_re.re_data_tables was not found in location US
    
    (job ID: 62bf3af6-1656-4fb2-88d0-42166b550568)

2021-08-02 10:07:53.710829 (MainThread): unclosed running multiprocessing pool <multiprocessing.pool.ThreadPool state=RUN pool_size=4>

**Comment by mateuszklimek** [comment]
@dbrtly Thanks for submitting the issue! I can confirm it happens also for me when doing `dbt compile` I expect it's related to referencing `re_data_tables` in macro and I'm investigating it.

In the meantime, just making sure it's clear `dbt run` should work properly for this it, and after initial tables are created by run `dbt compile` works (also in case of running dbt run you don't need to create dataset yourself, it will be created by run) And regarding that, I wonder if `dbt compile` error is something blocking you, or something which could be replaced with calling `dbt run` instead.

**Comment by dbrtly** [comment]
dbt compile is a core command. I don't understand how ca
I tried this using the example project toy_shop after getting a postgres connection setup.

``` shell
(.venv) daniel@dbrtly-MBP toy_shop % dbt compile              
Running with dbt=0.18.1
Encountered an error:
Compilation Error in model row_counts (models/health/row_counts.sql)
  Model 'model.toy_shop.row_counts' (models/health/row_counts.sql) depends on a node named 're_data_row_count' which was not found
(.venv) daniel@dbrtly-MBP toy_shop % dbt run              
Running with dbt=0.18.1
Encountered an error:
Compilation Error in model row_counts (models/health/row_counts.sql)
  Model 'model.toy_shop.row_counts' (models/health/row_counts.sql) depends on a node named 're_data_row_count' which was not found
```
then I upgraded dbt and got this
``` shell
(.venv) daniel@Daniels-MBP toy_shop % dbt compile 
Running with dbt=0.20.0
Found 22 models, 41 tests, 0 snapshots, 0 analyses, 414 macros, 0 operations, 3 seed files, 3 sources, 0 exposures

12:05:22 | Concurrency: 4 threads (target='dev')
12:05:22 | 
Encountered an error:
Runtime Error
  Database Error in model re_data_freshness_inc (models/intermediate/re_data_freshness_inc.sql)
    relation "toy_shop_re.re_data_tables" does not exist
    LINE 5:     from "toy_shop"."toy_shop_re"."re_data_tables"
```

another experiment:

``` shell
dbt run
```

this mostly works but model pending_orders refers to a source that doesn't exist.

``` shell
select * from {{ source('toy_shop', 'orders') }} where status = 'pending'
```

**Comment by dbrtly** [comment]
It works if I strictly follow the instructions of the demo but I 'm trying to figure out how to actually use it on a project.

**Comment by mateuszklimek** [comment]
Hey @dbrtly to update you on this. I think I know why `dbt compile` fails. TLDR; it's most likely because on how macros for inspecting tables are implemented. but do not yet know what would be a clean solution for this. Actually asked about that in dbt slack channel 🙂  and will update you on it.

Currently skipping compile is the best workaround.

**Comment by mateuszklimek** [comment]
Hey, @dbrtly I have some updates on this. I think I know why dbt compile fails. TLDR; it's most likely because of how macros for inspecting tables are implemented in re_data. I'm not sure yet what would be a clean solution for this. Actually asked about that in dbt slack channel 🙂  and will update you on it. I also saw some other packages had the same issues you are describing here.

Currently skipping compile is the best workaround. Also just to update why it doesn't fail when doing dbt run. dbt compile is actually not a prerequisite to running dbt run and the logic for it is quite different. I believe it's mostly to be used for debugging purposes. Linking dbt docs here: https://docs.getdbt.com/reference/commands/compile most likely you already saw it...

Also if you need help with how to set up re_data inside your projects I will be happy to talk about this either on our [Slack](https://www.getre.io/slack) or just via 1-1 [call](https://calendly.com/mateuszklimek/30min?month=2021-08). I think now I would need a bit more details for your use case and other models that you have to help with that.

Hope it helps! 🙂

**Comment by mateuszklimek** [comment]
@dbrtly This should be solved by 0.2.1. Let me know if you manage to confirm that it works as expected now 🙂
